[project]
name = "detect128"
version = "0.1.0"
description = "Project for 'Code 128' barcodes detection"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ultralytics>=8.3.248",
]

[dependency-groups]
dev = [
    "dvc[s3]>=3.65.0",
]
